# Generated by Django 3.1.3 on 2020-11-21 14:33

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountinformation',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('createdate', models.DateField(db_column='createDate')),
                ('remark', models.CharField(default='无备注', max_length=200)),
                ('casenumber', models.IntegerField(db_column='caseNumber', default=0)),
                ('authority', models.CharField(default='普通用户', max_length=50)),
            ],
            options={
                'db_table': 'accountinformation',
            },
        ),
        migrations.CreateModel(
            name='Casedata',
            fields=[
                ('caseid', models.AutoField(db_column='caseID', primary_key=True, serialize=False)),
                ('casename', models.CharField(db_column='caseName', default='未命名', max_length=50)),
                ('citynumber', models.IntegerField(db_column='cityNumber')),
                ('roadnumber', models.IntegerField(db_column='roadNumber')),
                ('inittotal', models.BigIntegerField(db_column='initTotal')),
                ('inittotalinfected', models.BigIntegerField(db_column='initTotalInfected')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.accountinformation')),
            ],
            options={
                'db_table': 'casedata',
            },
        ),
        migrations.CreateModel(
            name='Initcitydata',
            fields=[
                ('cityid', models.AutoField(db_column='cityID', primary_key=True, serialize=False)),
                ('cityname', models.CharField(db_column='cityName', max_length=50)),
                ('initpop', models.BigIntegerField(db_column='initPop', default=0)),
                ('initinfect', models.BigIntegerField(db_column='initInfect', default=0)),
                ('caseid', models.ForeignKey(db_column='caseID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.casedata')),
            ],
            options={
                'db_table': 'initcitydata',
            },
        ),
        migrations.CreateModel(
            name='Modeldata',
            fields=[
                ('layerid', models.AutoField(db_column='layerID', primary_key=True, serialize=False)),
                ('layername', models.CharField(db_column='layerName', max_length=20)),
                ('layerparm', models.CharField(db_column='layerParm', max_length=20)),
            ],
            options={
                'db_table': 'modeldata',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('themeno', models.AutoField(db_column='themeNo', primary_key=True, serialize=False)),
                ('themename', models.CharField(db_column='themeName', max_length=50)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Cityposition',
            fields=[
                ('cityid', models.OneToOneField(db_column='cityID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.initcitydata')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            options={
                'db_table': 'cityposition',
            },
        ),
        migrations.CreateModel(
            name='Logindata',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.accountinformation')),
                ('userpassword', models.CharField(db_column='userPassword', max_length=20)),
                ('salt', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'logindata',
            },
        ),
        migrations.CreateModel(
            name='Personalprofile',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend.accountinformation')),
                ('avatar', models.ImageField(upload_to=backend.models.user_directory_path, verbose_name='头像')),
                ('username', models.CharField(db_column='userName', max_length=50)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=11)),
                ('sex', models.CharField(default='保密', max_length=10)),
                ('address', models.CharField(default='保密', max_length=200)),
                ('email', models.CharField(db_column='Email', default='保密', max_length=50)),
                ('birth', models.DateField()),
            ],
            options={
                'db_table': 'personalprofile',
            },
        ),
        migrations.CreateModel(
            name='Initroaddata',
            fields=[
                ('roadid', models.AutoField(db_column='roadID', primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('volume', models.BigIntegerField()),
                ('caseid', models.ForeignKey(db_column='caseID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.casedata')),
            ],
            options={
                'db_table': 'initroaddata',
            },
        ),
        migrations.CreateModel(
            name='Dailyforecastdata',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('population', models.BigIntegerField()),
                ('infected', models.BigIntegerField()),
                ('cityid', models.ForeignKey(db_column='cityID', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.initcitydata')),
            ],
            options={
                'db_table': 'dailyforecastdata',
            },
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='themeno',
            field=models.ForeignKey(db_column='themeNo', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.theme'),
        ),
    ]
