# Generated by Django 3.1.3 on 2020-11-22 08:20

import backend.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='avatar',
            field=models.ImageField(default='defaultFiles/defaultAvatar.png', upload_to=backend.models.user_directory_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='birth',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
