# Generated by Django 3.1.3 on 2020-11-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201122_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedata',
            name='userid',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='backend.accountinformation'),
        ),
        migrations.AlterField(
            model_name='cityposition',
            name='cityid',
            field=models.OneToOneField(db_column='cityID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.initcitydata'),
        ),
        migrations.AlterField(
            model_name='dailyforecastdata',
            name='cityid',
            field=models.ForeignKey(db_column='cityID', on_delete=django.db.models.deletion.CASCADE, to='backend.initcitydata'),
        ),
        migrations.AlterField(
            model_name='initcitydata',
            name='caseid',
            field=models.ForeignKey(db_column='caseID', on_delete=django.db.models.deletion.CASCADE, to='backend.casedata'),
        ),
        migrations.AlterField(
            model_name='initroaddata',
            name='caseid',
            field=models.ForeignKey(db_column='caseID', on_delete=django.db.models.deletion.CASCADE, to='backend.casedata'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='userid',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.accountinformation'),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='userpassword',
            field=models.CharField(db_column='userPassword', max_length=32),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='avatar',
            field=models.ImageField(default='defaultFiles/defaultAvatar.png', upload_to='media/avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='userid',
            field=models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.accountinformation'),
        ),
    ]
