# Generated by Django 3.1.3 on 2020-11-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201122_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CaseData',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='backend.AccountInformation'),
        ),
        migrations.AlterField(
            model_name='CityPosition',
            name='cityId',
            field=models.OneToOneField(db_column='cityId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.InitCityData'),
        ),
        migrations.AlterField(
            model_name='DailyForecastData',
            name='cityId',
            field=models.ForeignKey(db_column='cityId', on_delete=django.db.models.deletion.CASCADE, to='backend.InitCityData'),
        ),
        migrations.AlterField(
            model_name='InitCityData',
            name='caseId',
            field=models.ForeignKey(db_column='caseId', on_delete=django.db.models.deletion.CASCADE, to='backend.CaseData'),
        ),
        migrations.AlterField(
            model_name='InitRoadData',
            name='caseId',
            field=models.ForeignKey(db_column='caseId', on_delete=django.db.models.deletion.CASCADE, to='backend.CaseData'),
        ),
        migrations.AlterField(
            model_name='LoginData',
            name='userId',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.AccountInformation'),
        ),
        migrations.AlterField(
            model_name='LoginData',
            name='userPassword',
            field=models.CharField(db_column='userPassword', max_length=32),
        ),
        migrations.AlterField(
            model_name='PersonalProfile',
            name='avatar',
            field=models.ImageField(default='defaultFiles/defaultAvatar.png', upload_to='media/avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='PersonalProfile',
            name='userId',
            field=models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.AccountInformation'),
        ),
    ]
