# Generated by Django 3.1.3 on 2020-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201122_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedata',
            name='casemode',
            field=models.CharField(db_column='caseMode', default='自定案例', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='themecolour',
            field=models.CharField(db_column='themeColour', default='#FFFFFF', max_length=7),
            preserve_default=False,
        ),
    ]
