# Generated by Django 3.1.3 on 2020-12-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201214_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedata',
            name='casemode',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='themecolour',
        ),
    ]
