# Generated by Django 3.1.3 on 2020-12-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201219_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedata',
            name='caseMode',
            field=models.CharField(db_column='caseMode', default='自定模式', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='themeColour',
            field=models.CharField(db_column='themeColour', default='#FFFFFF', max_length=7),
            preserve_default=False,
        ),
    ]
