# Generated by Django 3.0.6 on 2020-12-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201219_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='createDate',
            field=models.DateField(auto_now_add=True, db_column='createDate'),
        ),
    ]
