# Generated by Django 3.1.3 on 2020-12-21 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201220_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinformation',
            name='createDate',
            field=models.DateField(db_column='createDate', default=django.utils.timezone.now),
        ),
    ]
