# Generated by Django 3.1.3 on 2020-12-21 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201221_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedata',
            name='caseCreateDate',
            field=models.DateField(db_column='caseCreateDate', default=django.utils.timezone.now),
        ),
    ]
